### ISSUE TITLE
ctrl with + not working

### ISSUE THREAD

**Issue by viperflame** [th-ch/youtube-music#1127]
ctrl with - works but their is an issue with ctrl with + , not working .. plzz resolve this . see what happened , its so small i cant see this
![Screenshot (72)](https://github.com/th-ch/youtube-music/assets/132129346/422a9a10-0822-476b-af8a-94283306e927)
![Uploading Screenshot (72).png…]()

**Comment by JellyBrick** [comment]
Fixed at #1163

**Comment by viperflame** [comment]
nope its not fixed still facing the issue with latest update
![Screenshot (183)](https://github.com/th-ch/youtube-music/assets/132129346/098598ac-b49e-4139-aeb0-b84013174139)

**Comment by JellyBrick** [comment]
> nope its not fixed still facing the issue with latest update ![Screenshot (183)](https://user-images.githubusercontent.com/132129346/273390057-098598ac-b49e-4139-aeb0-b84013174139.png)

It's not released yet.

**Comment by JellyBrick** [comment]
[v2.0.0](https://github.com/th-ch/youtube-music/releases/tag/v2.0.0) released!

If you using in-app-menu, please you Ctrl+I and Ctrl+O
