### ISSUE TITLE
"Remove Upgrade Button" doesn't remove upgrade button anymore

### ISSUE THREAD

**Issue by FQQD** [th-ch/youtube-music#1199]
Since today's interface update, the "Remove Upgrade Button" option doesn't remove the upgrade button anymore.

![image](https://github.com/th-ch/youtube-music/assets/96952506/4fe4ba18-e8e2-4338-8426-be4634823e04)

**Comment by pinkkuh** [comment]
this issue is actually related to the bypass-age restriction #1205 .. the remove upgrade button will work if the bypass-age restriction is disabled (in my case). you can reproduce this issue. try it if it's the same.

**Comment by JellyBrick** [comment]
Fixed at #1206

**Comment by Rairof** [comment]
please reopen this post as this issue still persists (at least on v3.2.2.0) due to the feature being inconsistent on hiding the button every time the app restarts
![image](https://github.com/th-ch/youtube-music/assets/107706560/a55c40dd-2d14-4b8e-a8a8-54374f007807)

**Comment by JellyBrick** [comment]
> please reopen this post as this issue still persists (at least on v3.2.2.0) due to the feature being inconsistent on hiding the button every time the app restarts ![image](https://private-user-images.githubusercontent.com/107706560/301845445-a55c40dd-2d14-4b8e-a8a8-54374f007807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDAwMTgsIm5iZiI6MTcwNzEzOTcxOCwicGF0aCI6Ii8xMDc3MDY1NjAvMzAxODQ1NDQ1LWE1NWM0MGRkLTJkMTQtNGI4ZS1hOGE4LTU0Mzc0ZjAwNzgwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMzI4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2YyYmI5MTFkODVkNDExMWY2YWQ5M2I3NDFhOWU4MmI4NTMyMjYyNmUyMGUwM2RkZWE3YjNlOGQ1Njc4MDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TrYqzf4JGnP0mu1E6G5o7Nu_cXZhCqgxfw4uYRaqxSY)

Can't reproduce. I can't see the upgrade button, only the sign-in button instead.

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1927268319
Not sure why it's inconsistent for me then, thanks anyways I guess

**Comment by Rairof** [comment]
here is a recording-

https://github.com/th-ch/youtube-music/assets/107706560/b6bf3d6a-ceb3-4980-ac5e-023628302d4e

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/7ac79d5b-0758-48f1-ba79-289be40e014a)

Try pressing `Ctrl+Shift+I` to open DevTools, click this button on the top right, and then click the Upgrade button. Then please take a screen capture of DevTools and send it to us.

@Rairof

**Comment by LoneWolf993** [comment]
Upgrade button still visible in 3.2.2.0

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1927268319
maybe it breaks when an account is signed in

**Comment by LoneWolf993** [comment]
> [#1199 (comment)](https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1927268319) maybe it breaks when an account is signed in

seems so

**Comment by JellyBrick** [comment]
> Upgrade button still visible in 3.2.2.0

Not released yet

**Comment by JellyBrick** [comment]
finally fixed!
Thanks for the detailed report 👍 

![image](https://github.com/th-ch/youtube-music/assets/16558115/51b4e97d-7d62-440e-b9b4-37ba4ab15e9c)

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1950752479
Seems like the fix didn't worked, I am in latest version 3.3.1.0
![image](https://github.com/th-ch/youtube-music/assets/107706560/9020aa03-184f-48e3-9c21-63b734dd2cb6)

**Comment by Insane-Owl** [comment]
Can confirm that this is still a problem in 3.3.2.0.
Button still only shows when signed in.

**Not Signed In**
![image](https://github.com/th-ch/youtube-music/assets/78328941/26988a63-8a85-4525-982d-184c7116063e)

**Signed In**
![image](https://github.com/th-ch/youtube-music/assets/78328941/a73243dc-caa2-4a0d-b3d2-f4462a11dc40)

**Comment by JellyBrick** [comment]
I don't know why this issue is not reproducible in my environment, maybe it's an A/B test?

**Comment by JellyBrick** [comment]
> [#1199 (comment)](https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1955724255) Probably not...try signing in with a google account then restart application

Yeah, I tried it and https://github.com/th-ch/youtube-music/commit/9f5651a8ba53d39b6e9bedd02af95cecd63d8a6f works fine

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1956519313
uh then can you try with multiple accounts to see if it really is A/B tests?

**Comment by Insane-Owl** [comment]
> [#1199 (comment)](https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1956519313) uh then can you try with multiple accounts to see if it really is `A/B tests`? If its really `A/B tests` google needs to get their priorities straight for trying experiments on upgrade button instead of fixing actual issues 💀💀

I don't think it's an A/B test. I logged in with 3 different accounts and the button was there for all 3

**Comment by JellyBrick** [comment]
> OK, I think I found a solution. I'm not sure if this will work for everyone, but it worked for me.
> 
> I had to completely uninstall YTM, and delete it's appdata folder, and then reinstall after that. apparently just using the updater didn't work.

hmm, maybe it's a cookie-related issue?

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1958567410
I don't think so as I clean-installed portable version and issue still persists

**Comment by Insane-Owl** [comment]
> [#1199 (comment)](https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1958567410) I don't think so as I clean-installed portable version and issue still persists

Try deleting the appdata folder for ytm. I think the portable version still accesses the appdata folder. That's why you remain logged in if you switch from the installer version to the portable version without logging out.

**Comment by Rairof** [comment]
https://github.com/th-ch/youtube-music/issues/1199#issuecomment-1975238426
what I meant clean install is that I uninstalled youtube music app from control panel then removed any youtube music folders from searching it in file explorer

**Comment by Rairof** [comment]
Update-
So, now after clean installing again, it works now for some reason
![image](https://github.com/th-ch/youtube-music/assets/107706560/989f5e3c-f5c6-4677-b3a6-41750b9290bb)

**Comment by now-its-dark** [comment]
I've also been having this issue on MacOS ARM version 3.3.6, just installed the app for the first time today. 
One thing I noticed, is that it seems somehow related to #1822 (which I am also experiencing) — when the Starting Page is set to "Unset", the Subscribe button disappears, when it is set to anything else, the button comes back.

**Comment by blankets2** [comment]
Came here looking for this, hopefully a fix. even though it was the least of my issues. I just downloaded it today, and everything was fine. I was setting it up, looks and stuff, that's when I noticed the upgrade button didn't disappear. but then, whenever we started again, and I went to play the first song, there were ads.. was I not supposed to log in with my. Google account? have my youtube stuff on there, and I thought it would work because of youtube revanced., but my phone broke, so I got to use pc, and I don't think it's on pc. I don't know.

**Comment by Insane-Owl** [comment]
> I've also been having this issue on MacOS ARM version 3.3.6, just installed the app for the first time today. One thing I noticed, is that it seems possibly related to #1822 (which I am also experiencing) — when the Starting Page is set to "Unset", the Subscribe button disappears, when it is set to anything else, the button comes back.

I believe this is the root cause!

**Comment by AD094** [comment]
Fix - that worked for me:
1. Options> Resume last song when app starts (ON)
2. (Optional setting) > Plugins > Disable autoplay (both options on)

The solution is to keep something in song queue playing (or paused) & upgrade button won't show up.
