### ISSUE TITLE
KDE media plasmoid does not receive album art

### ISSUE THREAD

**Issue by SomeAspy** [th-ch/youtube-music#1236]
I bring this issue up because it works with the YouTube Music website and the goal seems to give the same experience as the website (albeit, with an enhanced feature set)

This is on arch linux, using the AUR package [aur.archlinux.org/packages/youtube-music-bin](https://aur.archlinux.org/packages/youtube-music-bin) @ 1.20.0-5

As shown below, in the first image this is using the app. Image data is not sent to the KDE Media player 

I kinda looked around a little for documentation on how to integrate with this, but I was unable to find anything. However, it is included in KDE desktop.
![image](https://github.com/th-ch/youtube-music/assets/33640860/331d8579-ee6c-474e-832c-9cc935f7c4dd)

Below is shown with the application
![image](https://github.com/th-ch/youtube-music/assets/33640860/d2ab67b0-3cf0-419b-b1c0-d49ff95ff985)

And this is with music.youtube.com on firefox:
![image](https://github.com/th-ch/youtube-music/assets/33640860/db9305ab-3ab1-411d-abd4-ae6b69b8e63c)

I apologize for the lack of information in this issue (namely documentation on the media plasmoid) but I hope this is enough to work with

**Comment by JellyBrick** [comment]
![image](https://github.com/th-ch/youtube-music/assets/16558115/1181a37e-6e7d-4910-ba72-c6de0a37e7d1)

Fixed in #1291

**Comment by SomeAspy** [comment]
@JellyBrick despite using the [youtube-music-git](https://aur.archlinux.org/packages/youtube-music-git) AUR package, this appears to still not work 
![image](https://github.com/th-ch/youtube-music/assets/33640860/4ced1e53-82e2-4ffc-a449-1d8dfbe696f8)

**Comment by JellyBrick** [comment]
> @JellyBrick despite using the [youtube-music-git](https://aur.archlinux.org/packages/youtube-music-git) AUR package, this appears to still not work ![image](https://user-images.githubusercontent.com/33640860/274388374-4ced1e53-82e2-4ffc-a449-1d8dfbe696f8.png)

How about [this AUR](https://aur.archlinux.org/packages/youtube-music-bin) package?

**Comment by SomeAspy** [comment]
Hi, sorry for lack of response, been busy with school work - I will get to this soon

**Comment by SomeAspy** [comment]
the youtube-music-bin aur has the same issue.

**Comment by JellyBrick** [comment]
Please enable the `shortcuts` plugin
