### ISSUE TITLE
[Bug]: Discord RPC isn't working

### ISSUE THREAD

**Issue by patYczakus** [th-ch/youtube-music#1524]
### 1st
Ok, it works, but it loaded too long

### 2nd
So this plugin works fine, but it didn't show first music played after start

### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Last Known Working YouTube Music (Application) version

1.20.0 (I used for a long time)

### Reproduction steps

Just "enable" Discord RPC (set to turn on)

### Expected Behavior

- Rich Presence working normally
- Information about enabled plugin

### Actual Behavior

- Rich Presence isn't working even thought I have showing RPC option checked
- In logs no information about enabling or error about that<br />
![image](https://github.com/th-ch/youtube-music/assets/75316297/0cf9f1a9-e441-446b-b6e3-dd42444ebe6e)

### Enabled plugins

1. Adblock
2. **Discord RPC** (required)
3. In-App menu
4. Album color theme
5. Navigation
6. Precise volume

**Comment by patYczakus** [comment]
Of course logs are in polish, but I think you can see that's no plugin enabled (in quotes)

**Comment by JellyBrick** [comment]
fixed at https://github.com/th-ch/youtube-music/commit/5fa88b5ce92de5a2323c20206bfe9bd7f66f6193

**Comment by spectrum705** [comment]
Btw how to use Discord RPC?  I have it enabled but it's not really working for me .
![image](https://github.com/th-ch/youtube-music/assets/55865953/c37251f5-b143-4628-b755-aeaee28ff9b6)

**Comment by ArjixWasTaken** [comment]
Discord needs to be running

**Comment by spectrum705** [comment]
> Discord needs to be running

it is running. how to connect ytmusic to discord tho?

**Comment by JellyBrick** [comment]
> > Discord needs to be running
> 
> it is running. how to connect ytmusic to discord tho?

If the RPC doesn't work, try clicking the `Connected` button again.

**Comment by spectrum705** [comment]
Nothing happenes when i pressed it 
![image](https://github.com/th-ch/youtube-music/assets/55865953/8d0776a2-497d-404c-9168-207c9a2f41da)

**Comment by patYczakus** [comment]
> Btw how to use Discord RPC? I have it enabled but it's not really working for me . ![image](https://private-user-images.githubusercontent.com/55865953/291056489-c37251f5-b143-4628-b755-aeaee28ff9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQ4MTIsIm5iZiI6MTcwMjg0NDUxMiwicGF0aCI6Ii81NTg2NTk1My8yOTEwNTY0ODktYzM3MjUxZjUtYjE0My00NjI4LWI3NTUtYWVhZWUyOGZmOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjBkMGU1YmIzYWEzOGE0ZjdkMWZhOTZlYWFiNTZmYTRjYjk1MTFiYzc3MzQ2OGIwZTg2ZmRhMmQ5MjMzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.demcus7qMwppK2Y-pEJIgKOPYnTCS7VO_rkKTMkYg8A)

In my YT Music RPC won't work too on start, you **must** wait some time to run on (in my situation - 30 minutes +- 10 min)

**Comment by spectrum705** [comment]
> > Btw how to use Discord RPC? I have it enabled but it's not really working for me . ![image](https://private-user-images.githubusercontent.com/55865953/291056489-c37251f5-b143-4628-b755-aeaee28ff9b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NDQ4MTIsIm5iZiI6MTcwMjg0NDUxMiwicGF0aCI6Ii81NTg2NTk1My8yOTEwNTY0ODktYzM3MjUxZjUtYjE0My00NjI4LWI3NTUtYWVhZWUyOGZmOWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDIwMjE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjBkMGU1YmIzYWEzOGE0ZjdkMWZhOTZlYWFiNTZmYTRjYjk1MTFiYzc3MzQ2OGIwZTg2ZmRhMmQ5MjMzNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.demcus7qMwppK2Y-pEJIgKOPYnTCS7VO_rkKTMkYg8A)
> 
> In my YT Music RPC won't work too on start, you **must** wait some time to run on (in my situation - 30 minutes +- 10 min)
yeah it doesnt work for me even after 30 mins, idk why. How do i connect my discord account with ytmusic? i dont remember doing that?

**Comment by JellyBrick** [comment]
Finally fixed at da3bc5aeb7a7bd700cd4a4ce24a2163591e88faf

**Comment by spectrum705** [comment]
> Finally fixed at [da3bc5a](https://github.com/th-ch/youtube-music/commit/da3bc5aeb7a7bd700cd4a4ce24a2163591e88faf)

ohh nicee. so how do i use it?

**Comment by JellyBrick** [comment]
> > Finally fixed at [da3bc5a](https://github.com/th-ch/youtube-music/commit/da3bc5aeb7a7bd700cd4a4ce24a2163591e88faf)
> 
> ohh nicee. so how do i use it?

We'll release a new version soon.

**Comment by spectrum705** [comment]
oh okay, can't wait for it.

**Comment by JellyBrick** [comment]
> oh okay, can't wait for it.

@spectrum705 We've released 3.1.1 which fixes this issue

**Comment by spectrum705** [comment]
> > oh okay, can't wait for it.
> 
> @spectrum705 We've released 3.1.1 which fixes this issue

oh just 30 mins ago, let me try.

**Comment by spectrum705** [comment]
its enabled but still not showing on my discord. is there something else I need to do?

![image](https://github.com/th-ch/youtube-music/assets/55865953/937e276c-b11b-4a64-ab6f-2d76eaad60b8)

**Comment by JellyBrick** [comment]
Did you enable "Show Game Activity" in Discord?

**Comment by spectrum705** [comment]
Okay I enabled it and it's working now. Thank you so much :)

**Comment by spectrum705** [comment]
Hi, 
it doesnt update the songs if the discord is minimized in the system tray, they only get updated when I open it at the top.

**Comment by JellyBrick** [comment]
> Hi, it doesnt update the songs if the discord is minimized in the system tray, they only get updated when I open it at the top.

This is a bug in the Discord (not an issue with the YTMD)

**Comment by spectrum705** [comment]
ohh okay

**Comment by inson1** [comment]
@spectrum705 isnt this bug?
![brave_GHVUO30JHx](https://github.com/th-ch/youtube-music/assets/75314629/297e9cdc-9079-41b3-a7f5-43b913dce8c4)

**Comment by inson1** [comment]
@spectrum705 How did you move the search to left? :)

**Comment by spectrum705** [comment]
> @spectrum705 isnt this bug? wh it is black? 
the top banner thing? idk but its changing with the song's album color.
and i dont really remember how the search bar is at left, probably tweaked something or its by default, sorry 😅

**Comment by patYczakus** [comment]
> *spectrum705* isnt this bug? wh it is black?

@inson1, **BRO**, I just opened for my problem not about colored theme, but RPC
*//and yes, it is a bug*
