### ISSUE TITLE
[Bug]: Can't play content added from RSS feed such as podcast from soundcloud CORS issue?

### ISSUE THREAD

**Issue by t3nk3y** [th-ch/youtube-music#1620]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.2.2

### Are you using the portable version of the YouTube Music Application?

- [ ] I use the portable version of the YouTube Music Application.

### What operating system are you using?

Other Linux

### Operating System Version

Garuda Linux 6.7.0-AMD-znver2 (64-bit), KDE Plasma 5.27.10

### What arch are you using?

x64

### Reproduction steps

1. Open a track from an RSS/external audio source.
2. Press play, it won't work.
To add an RSS source:
1. Go to Library
2. Click Podcasts (chip below Library tab in header)
3. Click Add podcast
4. Choose Add RSS feed
5. Enter a podcast RSS feed URL, such as: https://feeds.soundcloud.com/playlists/soundcloud:playlists:432476748/sounds.rss

### Expected Behavior

External track plays from YT music.

### Actual Behavior

External resource shows a 403 error, followed by an info message stating that the audio outputs all 0's due to CORS access restrictions.  (This doesn't happen in Chrome or Firefox), and I assume is due to a client side CORS restriction.

![image](https://github.com/th-ch/youtube-music/assets/26716328/c5df8273-415c-43cc-91fc-099c7c0b1d8d)

```
GET https://cf-media.sndcdn.com/Aebn75mGDwqR?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vQWVibjc1bUdEd3FSKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNDkwNjE3M319fV19&Signature=M3d7fvyrYxgQvG5sqDRdYSQMBjoqLr2eRcaikvnsP4U3njypIQKblosfnoGkDysOEFrt-cYfzVbPlxjzKhArZ5dGpRfzYqDI4O3hK2kQOl9611kLw8z7vvnuZ0viCebAm7pN4h2LLeWKDGo5agNfLxv0C3ytkcty4biqu8KiQU2~Eo5aDBYkWyVNXCP3PSjGciMC4LesfbcQiL~lUzfeKGOXD1Q0BN3nMSZG-Gkk8WSYM12vXtCjTip-~aNGPbLc4Okntvi~1H0JmDyIhyOPZRCDmuUopp3vVYfTZJ7mjxYcjJ9VAYg3v5EZQxd7UGTHp4ybjHBYRiL8mGf54SRSOg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ 403 (Forbidden)
```
```
MediaElementAudioSource       /watch?v=OikBtHRKIRY&list=PLIxxqUUjNJMDW_5X-zjMxGBKbcS9p_08s:1 
outputs zeroes due to CORS access restrictions for https://www.podtrac.com/pts/redirect.mp3/feeds.soundcloud.com/stream/887295340-lemme-listen-the-ensigns-log-podcast-episode-066-just-a-little-empathy.mp3
```

### Enabled plugins

1. Discord Rich Presence
2. Exponential Volume
3. In-App Menu
4. Navigation
5. Shortcuts (& MPRIS)
6. Video Toggle

**Comment by JellyBrick** [comment]
I can reproduce this issue, but I can't figure out why - maybe it's a bug in Electron?

**Comment by JonUleis** [comment]
Would be great if we could listen to podcasts in the app now that Google Podcasts is folding into YTM. On my app they appear to be playing (the time/duration advances each second, play icon switches to pause) but no audio plays.

**Comment by Proulxs** [comment]
Issue still present on v3.3.6 portable for me. Youtube made me move my podcast today since they are shutting down but Youtube Music app doesn't work to play them. No issue on music.youtube website so doesn't seem to be on their side.

**Comment by Insane-Owl** [comment]
same Issue on v3.3.12

**Comment by MulverineX** [comment]
This is probably an issue with the CSP headers being received from YouTube, the app needs a way to remove these.

**Comment by MulverineX** [comment]
https://github.com/electron/electron/issues/19775#issuecomment-1001643667

**Comment by Insane-Owl** [comment]
Any updates on this Issue?

**Comment by Lordmau5** [comment]
Just moved my Spotify library over to YT Music and found out about this app

Sadly also running into this issue with 3.6.0 :(

**Comment by JellyBrick** [comment]
fixed at https://github.com/th-ch/youtube-music/commit/77bfe8e218ce606f6b78ae194fbd40321fbd7ce5

Thanks to @MulverineX and @Lordmau5!

**Comment by Lordmau5** [comment]
The protocol approach seems like the more elegant way - very happy to hear that it was an easy fix

Didn't mention it before but thank you and the team for making a nice, extensible wrapper around the YT Music app! 😁

**Comment by JellyBrick** [comment]
@Lordmau5 Still reproducible this issue after 3.6.2?

**Comment by ArjixWasTaken** [comment]
In my synced-lyrics PR I had to fix CORS because the current fix was not working for me, maybe that also fixes this issue?

https://github.com/ArjixWasTaken/youtube-music/blob/synced-lyrics/src/index.ts#L901-L916

**Comment by Lordmau5** [comment]
> In my synced-lyrics PR I had to fix CORS because the current fix was not working for me, maybe that also fixes this issue?
> 
> [ArjixWasTaken/youtube-music@`synced-lyrics`/src/index.ts#L901-L916](https://github.com/ArjixWasTaken/youtube-music/blob/synced-lyrics/src/index.ts#L901-L916)
> 
> ```ts
> betterSession.webRequest.onHeadersReceived((details, callback) => {
>     details.responseHeaders ??= {};
> 
>     // prettier-ignore
>     if (new URL(details.url).protocol === 'https:') {
>       // Remove the content security policy
>       delete details.responseHeaders['content-security-policy-report-only'];
>       delete details.responseHeaders['content-security-policy'];
> 
>       // Only allow cross-origin requests from music.youtube.com
>       delete details.responseHeaders['access-control-allow-origin'];
>       details.responseHeaders['access-control-allow-origin'] = ['https://music.youtube.com'];
>     }
> 
>     callback({ cancel: false, responseHeaders: details.responseHeaders });
>   });
> ```

Tried with this code in the master branch, unfortunately still getting the same error and no audio

**Comment by JellyBrick** [comment]
fixed by https://github.com/th-ch/youtube-music/commit/533b96d1f6f2254027b4a0e7ba9187f2e34e3ced

**Comment by Lordmau5** [comment]
Not sure why it was closed when I said it wasn't fixed.

It still doesn't play with 3.7.0 and throws this error in the console:
```
MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://pdst.fm/e/mgln.ai/e/135/chrt.fm/track/8E527/verifi.podscribe.com/rss/p/swap.fm/track/i7NUCPwi3tJP053nG6mP/traffic.megaphone.fm/STU8887385542.mp3?updated=1733727613
```

**Comment by JellyBrick** [comment]
> Not sure why it was closed when I said it wasn't fixed.

I can't reproduce this issue when testing with this link (https://feeds.soundcloud.com/playlists/soundcloud:playlists:432476748/sounds.rss)

**Comment by Proulxs** [comment]
Still not working in version 3.7.1.0. I am using portable and trying to listen to BBC podcast or any of the MSNBC ones. I don't see where I can find the link to share within the app.
Podcast added from within the app by "Add a podcast" then find the podcast I want will work fine.
My podcasts were added "from a RSS feed" automatically by Google when I asked them to move my podcasts from the old Podcast app to youtube Music. I tried to find some of them on youtube music without much success.

**Comment by schwarztrinker** [comment]
I also experience this bug referring to a CORS problem - will append the error and link URL for further solution of the bug. Maybe that helps:

```
> GET https://i1.ytimg.com/vi/KB02hXSa-4k/mqdefault.jpg 404 (Not Found)
> MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://audio.podigee-cdn.net/1781138-m-285e597b2e3db882c55044131516d8c4.mp3?source=feed
```

**Comment by aldo-alcantar** [comment]
Justo confirm this issue is still present on 3.10.0.0

**Comment by JellyBrick** [comment]
Caused by this code..

https://github.com/th-ch/youtube-music/blob/26fa1f85b2774bf4badb593659290defe4cc26ef/src/renderer.ts#L308-L311

I have no idea how to fix it.

**Comment by JonUleis** [comment]
I took a crack at this and opened a PR: #4592

The root cause is the `MediaElementAudioSourceNode` set up in `renderer.ts`. By spec it outputs zeroes for cross-origin media that was not fetched in CORS mode, which is the podcast/RSS case. Songs are fine because they stream via MSE from a same-origin blob. Registering the privileged `corsEnabled` scheme was not enough on its own, because the `<video>` had no `crossorigin` attribute and the third-party responses had no `Access-Control-Allow-Origin` header.

The fix is two small changes: set `crossOrigin = 'anonymous'` on the `<video>`, and add `Access-Control-Allow-Origin: *` on `resourceType === 'media'` responses. Podcasts play with audio now, and normal playback is not affected because it uses MSE and a blob URL. Testing and details are in the PR.
