### ISSUE TITLE
[Bug]: audio cuts sporadically, every 10s 

### ISSUE THREAD

**Issue by avichou** [th-ch/youtube-music#2161]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.12 

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS 14.5

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Last Known Working YouTube Music (Application) version

none

### Reproduction steps

1. play a song with youtube music 
2. experience cuts in song, short 1/2s cuts every 10 seconds or so 

### Expected Behavior

the audio shouldnt cut at all, this behavior is only present with th-ch youtube-music

none of the other apps i've used present that issue. youtube music websites, pwa with chrome/safari, https://github.com/steve228uk/YouTube-Music, or any other 

### Actual Behavior

there's audio cuts , from 1/4s to 1/2s , every five, ten, or fifteen seconds. it's bloody annoying 

### Enabled plugins

none. i disabled all of them and all options as well 

### Additional Information

macbook air m1 

i can provide with recording if necessary 

https://github.com/th-ch/youtube-music/assets/86660671/b98df13b-23cc-4d56-8153-5a52ca091220

https://github.com/th-ch/youtube-music/assets/86660671/0f4acf6c-3036-4b7f-b721-32cf1b634912

**Comment by JellyBrick** [comment]
Duplicate of #2149

**Comment by avichou** [comment]
> Duplicate of #2149

That's not it . The interface isn't laggy. It's just the audio that cuts  intermittently 
Every 5 seconds there's a cut . At 0.05, then 0.10, then 0.15s 

I don't think it should be closed as the same issue. Only the sound cuts like if it was trying to reach a higher bandwidth

**Comment by ComGreed** [comment]
I experienced the same problem, but only in video mode. Disabling hardware acceleration fixed it for me.

**Comment by avichou** [comment]
> I experienced the same problem, but only in video mode. Disabling hardware acceleration fixed it for me.

i have just tried and sadly it fixes nothing...

**Comment by JellyBrick** [comment]
Probably fixed in `3.4.0`.

**Comment by avichou** [comment]
> Probably fixed in `3.4.0`.

Just tested and sadly the issue is still here and just as annoying , every 5/10s there's this annoying sound cut 

Perhaps is it because I downloaded my likes playlist using YouTube music premium ? Maybe it's what slowing it ? 

I tried uninstalling and reinstalling from scratch and after some time the issues comes back and never leaves 

I use brew install btw

**Comment by ass293** [comment]
存在同样的问题，就是听歌会卡顿，放着会停下等缓冲(不是代理的问题，其他任何的播放都没问题)。有解决的朋友吗？乐意协助发现什么代码的问题

**Comment by avichou** [comment]
> There are the same issues, where listening to music stutters, and it pauses to buffer (not related to proxy issues, as YouTube videos on Chrome web pages do not stutter). The playback on [steve228uk / YouTube-Music](https://github.com/steve228uk/YouTube-Music?tab=readme-ov-file) works fine under the same environment.
> 
> I have tried reinstalling, from different methods (GitHub, brew), and changing proxy software, but the problem of music playback pausing persists.
> 
> Are there any solutions for this issue?
> 
> Mac m1 16.4.1 YouTube Music version 3.5.2 (3.5.2)

found any fix ? i stopped using it but i'm considering reinstalling

**Comment by SomeAspy** [comment]
can this still be reproduced
