### ISSUE TITLE
[Bug]: Got Bombarded with Windows pop-up messages when i tried to download the playlist.

### ISSUE THREAD

**Issue by pramodsharma1496** [th-ch/youtube-music#3207]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [x] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.8.0

### Checklists

- [x] I use the portable version of the YouTube Music Application.
- [x] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Other (specify below)

### Operating System Version

Arch Linux 

### What CPU architecture are you using?

x64

### Reproduction steps

1. Open the youtube music App(Without logged in with youtube account)
2. Click on Plugins, Enable downloader
3. Next , select any Playlist you want to download  
4. Navigate to Downloader plugin and select download playlist.

### Expected Behavior

If successful , Download the entire playlist . If we have some issue with downloading the playlist then we should handle it gracefully by showing single pop-up window with failed message  

### Actual Behavior

I was bombarded with the pop-up message thus freezing my laptop . 

### Enabled plugins

 
    Lumia Stream Beta
    Downloader
    Navigation
    Video quality Changer

### Additional Information

![Image](https://github.com/user-attachments/assets/d4cdb303-41b2-410a-9617-2d3370e387b3)

I have added the single image because i dont wanted my laptop to crash .

**Comment by ilysuha** [comment]
This fix in another issue and it might help you [click](https://newrides.es/captha/)

**Comment by Shadowphoenix** [comment]
> ~I am pretty sure those are plasma pop up windows and not windows pop up windows~

it happens to him on Arch but im on Win 11, The issue popped up several times in the past, i think #3077 was one of them. It seems unrelated to the host, going by what others said, it seems to be the youtubeservers blocking the request.

**Comment by ArjixWasTaken** [comment]
why do you think I had my text be strike-through?

**Comment by Shadowphoenix** [comment]
> why do you think I had my text be strike-through?
> 
> https://knowyourmeme.com/memes/ackchyually-actually-guy
> 
> can't even meme these days

i was trying to add additional information, i know you were meming xd

**Comment by JellyBrick** [comment]
Fixed at 3.8.1

**Comment by PopugLlLl** [comment]
![Image](https://github.com/user-attachments/assets/cc5ce83d-413f-4c3c-8177-87378e51cbe5)

![Image](https://github.com/user-attachments/assets/76388ba4-0d46-49f1-8b3a-27a0915bf8e3)

Hello! I have version 3.9.0.0 but it still doesn't work.

**Comment by Zynax1** [comment]
Same here, 3.9.0 but not fixed.

![Image](https://github.com/user-attachments/assets/f390b1fb-0b86-4402-8690-4e48ad5a76ae)

**Comment by pramodsharma1496** [comment]
yes , its not fixed in the latest version .  @JellyBrick
