### ISSUE TITLE
[Bug]: App takes a long time to load (slow)

### ISSUE THREAD

**Issue by MainWire** [th-ch/youtube-music#3379]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [x] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.9.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

macOS

### Operating System Version

macOS sequoia 15.4.1

### What CPU architecture are you using?

arm64 (including Apple Silicon)

### Reproduction steps

Open the app, and wait for the app to be loaded

### Expected Behavior

UI loads as fast as the web version

### Actual Behavior

UI is much slower to load than the music.youtube.com website.

### Enabled plugins

1. Downloader
2. Bypass age restriction
3. Navigation
4. Unobtrusive player

### Additional Information

The UI was also slow to load on my previous windows laptop. This makes me wonder if this is a network issue, except I have never had any problem with any other app, and my network has always been fast and reliable.
The music.youtube website is fast, no problem
The app takes ∼30s to show a window and 10 more to load the UI. It's still a bit slow after the UI is loaded.
I have a pro M1
Don't hesitate to ask anything you need that could clarify the issue

**Comment by srinadhkesineni** [comment]
well, i think its your system problem. In my Windows 11 it took hardly 5 seconds to open the window and load the UI and run the music.

**Comment by franz-dc** [comment]
Can you try enabling the "Performance improvement" plugin?

**Comment by ArjixWasTaken** [comment]
Do you have hardware acceleration enabled?

**Comment by MainWire** [comment]
Thank you for your answers.

I have tried the performance imporvement plugin, same thing.
I have also tried to disable hardware acceleration, doesn't change anything.
It may be my system, but I never had any problem with internet, I'm lucky to have a very fast internet, and my macbook is new with macos installed recently, so that's weird.

**Comment by JellyBrick** [comment]
Can't reproduce on MacBook M4 Pro (macOS 15.5)

**Comment by Serj92** [comment]
I have same issue (macOS sequoia 15.5). Loading takes 25-35 sec

**Comment by schneidenbach** [comment]
Having the same issue on a M4 Max with 128GB of memory.

**Comment by moberemk** [comment]
Noticed this too since upgrading to 3.10 (M3 Pro/15.5). Playback in general feels glitchier and less responsive. Performance improvement plugin is also enabled

**Comment by dansauve** [comment]
3.10 is basically unusable for me; takes long to load, and once it does the UI is super slow. 3.9 works fine.

MacBook Pro, M4 Pro, 48GB RAM

**Comment by jscheel** [comment]
Same for me, 3.10 is unusable on my mbp, m4 pro, 128gb ram. Takes 30s to open, screen is blank, and app is unresponsive. Happy to help debug.

**Comment by JellyBrick** [comment]
Can you reproduce this issue without `Bypass age restriction`?

**Comment by JellyBrick** [comment]
Also, please check that the application is running on the Rosetta. (Please check if it is an arm64 native version.)

**Comment by MainWire** [comment]
Fixed with version 3.10.0 for me, did a reinstall and it opened in 5 seconds

**Comment by qiye45** [comment]
I also encounter this issue when my Mac is running on battery with Low Power Mode enabled — the app becomes noticeably slower. Once I plug it in or turn Low Power Mode off, the startup speed returns to normal.

**Comment by jscheel** [comment]
Just wanted to pop in and say that this issue is still happening on the new 3.11 release. Had to downgrade to 3.9 for the app to be responsive.

**Comment by NeDDy3z** [comment]
> Just wanted to pop in and say that this issue is still happening on the new 3.11 release. Had to downgrade to 3.9 for the app to be responsive.

Same here, downgrade helped. (on M4 24G)

**Comment by mcquenji** [comment]
could this be because of the intel emulation layer? my macbook prompted me to install rosetta in order to run this app

**Comment by dkillough** [comment]
Can replicate that this app is unbearably laggy (seemingly regardless of plugins) and have resorted to just adding youtube music as a safari web app for now. 

MacBook Pro M1 Max, manually installed using dmg while homebrew appears down.

Works fine on Windows 11 PC under the same account / settings.

**Comment by maddada** [comment]
App is very laggy here too. 

Macbook 16 Pro M2 Max 32gb. macOS 15.6. Version 3.11.0 of pear desktop. 

Tried with Performance Plugin enabled and disabled.

The app is using Intel arch and emulated which might be contributing.. hope this can be addressed..

<img width="969" height="331" alt="Image" src="https://github.com/user-attachments/assets/1b7b1504-4fd0-4fe5-acc0-971477e6c9c4" />

**Comment by Lashley93** [comment]
Same issue on an M4 Pro

**Comment by Cannabas3d** [comment]
Same issue on Windows 11. Ever since the latest update, it's extremely sluggish.

**Comment by JellyBrick** [comment]
> could this be because of the intel emulation layer? my macbook prompted me to install rosetta in order to run this app

<img width="1938" height="959" alt="Image" src="https://github.com/user-attachments/assets/ef9a1beb-30d3-4bd3-a80a-4880b711c8db" />

@maddada @mcquenji Could you check which file you downloaded? If it's asking for Rosetta, you might have downloaded the Intel version. Please make sure to download the file that ends with `3.11.0-arm64.dmg`, not `3.11.0.dmg`.

**Comment by JellyBrick** [comment]
cc @MainWire @Serj92 @dkillough @dansauve @schneidenbach @moberemk

**Comment by dkillough** [comment]
@JellyBrick Reinstalling now manually and will verify shortly; is there a homebrew tap I can use with an arm64 flag to make auto-updating a bit easier in the future?

**Comment by dkillough** [comment]
Reinstalling manually, for now, seems to be actually useable performance-wise. I already have Rosetta on my laptop so I guess I didn't see that prompt the first time? 

Fix: Download using the [latest version]`-arm64.dmg` file, then running the readme script to fix the "damaged and cannot be opened" popup: `/usr/bin/xattr -cr /Applications/`[appname]`.app` (replacing `[appname]` with the current name of the app).

Will update if becomes unusable again in the future :)
