### ISSUE TITLE
[Bug]: invisible plugin buttons

### ISSUE THREAD

**Issue by SilentNR** [th-ch/youtube-music#3589]
### Preflight Checklist

- [x] I use the latest version of YouTube Music (Application).
- [x] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [x] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.9.0

### Checklists

- [ ] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official version of (WEB) YTM](https://music.youtube.com).

### What operating system are you using?

Arch

### Operating System Version

6.15.4-arch2-1

### What CPU architecture are you using?

x64

### Expected Behavior

When enabling those plugins (Video Quality Changer, Synced Lyrics, Captions Selector), I expect to see and use their buttons

### Actual Behavior

Can't see but can use Video Quality Changer and Synced Lyrics buttons, Captions Selector don't do anything even when pressed 

<img width="369" height="92" alt="Image" src="https://github.com/user-attachments/assets/5a4f7890-ff48-49dc-907c-3a65f47f45b7" />

<img width="438" height="142" alt="Image" src="https://github.com/user-attachments/assets/bf6cf56b-3bfe-4b06-aced-1e8c2f6d760d" />

### Enabled plugins

those with problems : Synced Lyrics, Video Quality Changer, Captions Selector
other:
<img width="278" height="815" alt="Image" src="https://github.com/user-attachments/assets/69f158f6-a124-4a71-99d2-58a7edcb7a74" />

**Comment by JellyBrick** [comment]
Already fixed at https://github.com/th-ch/youtube-music/commit/e114e0ef445382f5fb1175db9c571edd93320a2e

**Comment by SilentNR** [comment]
Still have the issue, but only in my account, when i logout everything is working

**Comment by ArjixWasTaken** [comment]
@SilentNR please wait for the upcoming release
This issue is fixed in code, but it won't be fixed for you unless a new release is made, that includes that fix.
