### ISSUE TITLE
Last.fm scrobbler plugin doesn't create the app properly

### ISSUE THREAD

**Issue by DeRRudi77** [th-ch/youtube-music#571]
Hi all,

When trying to connect youtube-music to my last.fm account. I am able to go through the entire flow, but in the end, it doesn't create the app in my settings and scrobbling doesn't work. Any ideas on how to fix this? See screenshots for the flow. It all looks successful.

![image](https://user-images.githubusercontent.com/1484504/150815226-51829907-5853-4181-8cdf-395b84f46096.png)

I had this connection setup before, but removed it. Now re-adding seems to be a problem.

Rutger

**Comment by Araxeus** [comment]
could be the cause of #546 and #540
@semvis123 maybe a problem with the registered api_key/secret?
https://github.com/th-ch/youtube-music/blob/61eb23614a27a50e6901306f039cc7c0aed446db/config/defaults.js#L44-L45

**Comment by JellyBrick** [comment]
Fixed due to #1032

**Comment by Impasse52** [comment]
Is this PR merged in the latest release? Sadly this still doesn't work for me, and it seems like I can't build from source either. I get `npm ERR! Missing script: "build:linux"`.

**Comment by JellyBrick** [comment]
> Is this PR merged in the latest release? Sadly this still doesn't work for me, and it seems like I can't build from source either. I get `npm ERR! Missing script: "build:linux"`.

Use `npm run dist:linux`

**Comment by Impasse52** [comment]
Yep, this did the trick, thank you!
