### ISSUE TITLE
in-app menu plugin causes visual bug

### ISSUE THREAD

**Issue by SleepDaemon** [th-ch/youtube-music#924]
The background shouldn't be transparent and should remain solid black when scrolled. Also when ticking the blur-nav bar it doesn't take effect either. Many things in v1.18 don't work and so to anyone reading I suggest go back few versions where stuff is working.
![image](https://user-images.githubusercontent.com/88533953/208384418-6beb26c6-e975-45e3-a1e7-9f5a6e773454.png)

**Comment by Araxeus** [comment]
Sorry I was away for a while and some bugs pilled up.

I've opened a tiny pr which should fix this issue, feel free to share any other things that doesn't work!

**Comment by Jnss98b** [comment]
This bug happens if in-app-menu is enabled and the pr didn't fix it I don't think @Araxeus @th-ch 

In-app-menu enabled
![image](https://user-images.githubusercontent.com/24306400/231325648-819e7767-27df-49f3-9487-bc787914fa35.png)

In-app menu disabled
![image](https://user-images.githubusercontent.com/24306400/231325707-af5d0033-d58f-492c-baec-46366eef391b.png)
